### ISSUE TITLE
Ignore the '@' or '#' characters when processing the last word of a tweet

### ISSUE THREAD

**Issue by nacx** [cloudfakers/rhymestore#10]
When processing the last word of a tweet to see if it is a valid word (if not, the mention will be ignored), remove the '@' and '#' character at the beginning of the word to properly consider user names and hash tags.

**Comment by ssedano** [comment]
What a mess. Those commits are fails of indentation thou in my computer all seemed to be indented at the same level.

Sorry about that!

**Comment by nacx** [comment]
No worries. Thanks!
