### ISSUE TITLE
Start conversations pro-actively

### ISSUE THREAD

**Issue by nacx** [cloudfakers/rhymestore#11]
Make rimamelo start conversations pro-actively, expressing an opinion to random people tweets. This way we'll increase the probability to have people talking to rimamelo and will start more conversations and make more rhymes.

It would be desirable to start conversations with people that is geographically in a zone using language compatible with the loaded wordParser implementation.

**Comment by devvesa** [comment]
I wouldn't develop this feature this way. If I wouldn't know _rimamelo_ , it mentions me and I realize that's a bot, then I would report it as spam. 

Moreover, _rimamelo_ has a particular and intelligent sense of humor that many people couldn't get it :) That increases the chance of being reported as spam.

**Comment by ssedano** [comment]
Jaume's got a point here.

This can be implemented to only answer once to people that rimamelo actively reach them.

We can still tweeting with elfari bot.

**Comment by nacx** [comment]
Agree with both :)
